---
plugin: aws_ec2
keyed_groups:
  - key: tags
    prefix: tag

filters:
  # All instances with their state as `running`
  instance-state-name: running
  # All instances with their `environment` tag set to `sandbox`
  tag:environment: 
   - sandbox
