---
- name: Erase old BIRD config files
  import_tasks: erase_old_configs.yml

- name: "Template BIRD config: host specific part"
  import_tasks: template_bird_conf.yml

- name: "Template BIRD configs: kernel protocol for IPv4"
  import_tasks: template_kernel_ipv4.yml

- name: "Template BIRD configs: kernel protocol for IPv6"
  import_tasks: template_kernel_ipv6.yml

- name: "Template BIRD configs: static routes"
  import_tasks: template_static.yml

- name: "Template BIRD configs: IPv4"
  import_tasks: template_bgp_ipv4.yml

- name: "Template BIRD configs: IPv6"
  import_tasks: template_bgp_ipv6.yml

- name: "Template BIRD configs: direct"
  import_tasks: template_direct.yml

# Learning BIRD and experimenting with it
- name: "Template BIRD configs: experiments"
  import_tasks: experiment.yml
