---   
- name: Template BIRD config to /etc/bird.conf
  ansible.builtin.template:
    src: templates/bird.conf.j2
    dest: /etc/bird/bird.conf
    owner: bird
    group: bird
    mode: '0755'
  notify: Reload bird
  tags:
    - config
    - bird
