---
- name: Template per peer configs to /etc/bird/direct.conf
  ansible.builtin.template:
    src: templates/direct.j2
    dest: /etc/bird/direct.conf
    owner: bird
    group: bird
    mode: '0755'
  notify: Reload bird
  tags:
    - config
    - direct
