---
- name: Template per peer configs to /etc/bird/bgp_*_ipv6.conf
  ansible.builtin.template:
    src: templates/bgp_peer_ipv6.j2
    dest: /etc/bird/bgp_{{ tags.Name + '_to_' + peer.name }}_ipv6.conf
    owner: bird
    group: bird
    mode: '0755'
  loop: "{{ bgp_peers_ipv6 }}"
  loop_control:
    loop_var: peer
  notify: Reload bird
  tags:
    - config
    - bgp
    - ipv6

- name: Debug peer IPv6 address
  ansible.builtin.debug:
    msg: "{{ peer.peer_ip_address }}"
  loop: "{{ bgp_peers_ipv6 }}"
  loop_control:
    loop_var: peer
  notify: Reload bird
  tags:
    - config
    - bgp
    - ipv6