---
- name: Template per peer configs to /etc/bird/bgp_*.conf
  ansible.builtin.template:
    src: templates/bgp_peer_ipv4.j2
    dest: /etc/bird/bgp_{{ tags.Name + '_to_' + peer.name }}.conf
    owner: bird
    group: bird
    mode: '0755'
  loop: "{{ bgp_peers_ipv4 }}"
  loop_control:
    loop_var: peer
  notify: Reload bird
  tags:
    - config
    - bgp
    - ipv4
