---
- name: Template BIRD config to /etc/bird.conf
  ansible.builtin.template:
    src: templates/bird.conf.j2
    dest: /etc/bird/bird.conf
    owner: bird
    group: bird
    mode: '0755'
  notify:
    - Reload bird.service

# - name: 
  # ansible.builtin.debug:
    # msg: "{{ pr.name }}"
  # loop: "{{ bgp_peers }}"
  # loop_control:
    # loop_var: pr

- name: Template per peer configs to /etc/bird/bgp_*.conf
  ansible.builtin.template:
    src: templates/bgp_peer.j2
    dest: /etc/bird/bgp_{{ tags.Name + '_to_' + peer.name }}.conf
    owner: bird
    group: bird
    mode: '0755'
  loop: "{{ bgp_peers }}"
  loop_control:
    loop_var: peer
  notify:
    - Reload bird.service
