---
- name: Template kernel protocol for IPv4 to /etc/bird/kernel_ipv4.conf
  ansible.builtin.template:
    src: templates/kernel_ipv4.j2
    dest: /etc/bird/kernel_ipv4.conf
    owner: bird
    group: bird
    mode: '0755'
  notify: Reload bird
  tags:
    - config
    - kernel
    - ipv4
