---
- name: Template a file to /etc/network/interfaces.d/lo
  ansible.builtin.template:
    src: templates/lo.j2
    dest: /etc/network/interfaces.d/lo
    owner: root
    group: root
    mode: '0755'
  notify:
    - Restart networking service
  tags:
    - loopback
