---
- name: Sandbox playbook
  hosts: aws_ec2
  become: yes
  become_method: sudo
  
  tasks:

    - name: Ansible role - loopback
      include_role:
        name: loopback
  
    - name: Ansible role - bird_install
      include_role:
        name: bird_install

    - name: Ansible role - bird_configure
      include_role:
        name: bird_configure
