---
# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  tags:
    - ip_forwarding

- ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  tags:
    - ip_forwarding

# - ansible.posix.sysctl:
    # name: net.ipv6.conf.all.accept_ra
    # value: '1'
    # sysctl_set: yes
    # state: present
    # reload: yes
  # tags:
    # - ip_forwarding
